{% set name = "mapchete-eo" %}
{% set version = "2025.11.0" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/mapchete_eo-{{ version }}.tar.gz
  sha256: 1f13f8beb2571cb12916f6a40aae866040b4cc72ba9a1b7c4c2af4eff068d535

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  noarch: python

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
    - pip:
      - cql2
  run:
    - python >={{ python_min }}
    - click
    - croniter
    - lxml
    - mapchete >=2025.6.0
    - opencv
    - pillow
    - pydantic
    - pystac >=1.12.2
    - pystac-client >=0.7.5
    - retry
    - rtree
    - scipy
    - tqdm
    - xarray
    - pip
    - pip:
      - cql2

test:
  imports:
    - mapchete_eo
  commands:
    - pip check
    - mapchete eo --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/mapchete/mapchete-eo
  summary: Earth Observation–specific driver extensions for Mapchete
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ungarj
    - Scartography
